token:
  expiration: 864000000 # 10 days
  secret: '{cipher}AQAtyVakFOIpTmpI9Lm5W4LyxWdUlnpmm77x3Xrx5JwjxBJmLWjNQ4qEVYx6MSiCYc5P8O6OKUsDUbPCFsxv3sQLquyzxcTLSA4MmYs0gjATUGyt52wJPw+6Ju0xwfzCyqRC7gdLsHV8HKooY1cWEFCdBIRxouNHAJSvstGJEsoN9S/vIJHOh6zjiFQoibPxoV1dMC7i8b+jABPdA9rgxi+oE/eDP5FhZQ54PzXv6mg84WgFS4B1tRcvN3XxubPpy7CU2J7k8UdU2DFJ+PX9EC5LBsvRoRGQKmwgRsjdBCx8WQ7C75lMvScAoM951OgKpoDBWS65NNSmDLqKKIdT/OE1jMnaBMvbB6loxJ38zFTO6pHGmUFowXpPoHXpy8zKGWY='

gateway:
  ip: 192.168.35.61
